<?php

    define ('DS', DIRECTORY_SEPARATOR);
    define ('ISM_NS', 'ISM');

    $localAppISM = __DIR__. DS . 'app' . DS . ISM_NS;

    $source = __DIR__ . DS . ".." . DS . "acceptance" . DS . "WebGuy.php";
    $target = $localAppISM . DS . "AbstractPage.php";

    $source = realpath($source);
    $target = realpath($target);

    echo "Reading" . $source . PHP_EOL;

    $newMethods = array();
    $handle = fopen($source, "r");

    if ($handle) {
        while (($line = fgets($handle)) !== false) {
            $matches = array();
            $result = preg_match('~public function (.*) {~', $line, $matches);
            if ($result) {
                $newMethods[] = " * @method \\ISM\\BasePage " . $matches[1];
            }
            unset($matches);
        }
    } else {
        echo "Error in open file " . $source;
        die();
    }

    fclose($handle);
    $handleTarget = fopen($target, "r");

    if ($handleTarget) {
        $beginProxiedGenerateAutoBlock = false;
        $endProxiedGenerateAutoBlock = false;
        $lines = array();

        while (($line = fgets($handleTarget)) !== false) {
            $matches = array();

            if ( $beginProxiedGenerateAutoBlock ) {
                $resultEnd = preg_match('~# autogenerated-proxied-methods-end~', $line, $matches);
                if ($resultEnd) {
                    $beginProxiedGenerateAutoBlock = false;
                }
            }

            if ( !$beginProxiedGenerateAutoBlock ) {
                $resultBegin = preg_match('~# autogenerated-proxied-methods-start~', $line, $matches);
                if ($resultBegin) {
                    $lines[] = $line;
                    $beginProxiedGenerateAutoBlock = true;
                    foreach($newMethods as $method) {
                        $lines[] = $method . PHP_EOL;
                    }
                }
            }

            if ( $beginProxiedGenerateAutoBlock == false ) {
                $lines[] = $line;
            }

            unset($matches);
        }
    } else {
        echo "Error in open file " . $target;
        die();
    }

    fclose($handleTarget);

    $handleTarget = fopen($target, "w");

    if ($handleTarget) {
       foreach($lines as $line) {
           fputs($handleTarget, $line);
       }
    }

    fclose($handleTarget);